### ISSUE TITLE
[FR] Ability to request a fee for a hypothetical transaction

### ISSUE THREAD

**Issue by kyledcline** [GemHQ/round-rb#13]
In order to estimate a transaction's total, it would be useful to be able to submit a hypothetical payment and have returned Gem's calculated fee. This hypothetical response can have any expectation of an expiration, such as 5 or 10 seconds.

#### Code example

```ruby

# attempt mock payment
@mock_payment = account.mock_pay payees
# OR
@mock_payment = account.pay payees, mock: true

  => { "type" => "outgoing",
       "key" => nil,
       "data" => {
         "value" => 100000,
         "fee" => 11337,
         ...
       }
     }

# what kind of fee should I tell the user to expect?
@mock_payment[:data][:fee]
  => 11337
```

**Comment by joshua-bv** [comment]
closing as you can accomplish this by generating an unsigned transaction and pull the fee from the attributes
